name = "blue-wave-showcase"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
routes = [
  { pattern = "blue-wave-purifiers.pages.dev", custom_domain = true }
]

[[env.production.rules]]
type = "Text"
globs = ["**/*.html"]
compress = true